### ISSUE TITLE
Core doesn't seem to be running

### ISSUE THREAD

**Issue by b-mag** [obsidian-dot-dev/openFPGA-Vectrex#5] opened 2024-02-26 03:40 UTC
Perhaps user error.  After adding necessary files.  Adding needed games files in .vec.  Then running core it brings up the Assets > vectrex > common folder and lists said game.

Once I click game it refreshes interface screen to the same location but lacks all listings of games.  Does not launch game like typical cores I've run in the past.

1) I want to say that even though I can't get it to work this is a fantastic release, thank you and
2) your instructions make me believe this is not user error as they are very simple... but maybe I'm doing something wrong?

**Comment by b-mag** [comment] 2024-02-26 05:05
Someone elsewhere said you must select a .ovr after selecting game?

**Comment by b-mag** [comment] 2024-02-26 15:01
The above is correct. You MUST select an .ovr regardless of if you have or want one. My suggestion in the COMMON folder have a folder OVERLAYS where overlays with the exact same name plus ext .ovr are placed. Once user selects game (in .Vec or .bin) it tries to auto load same name overlay. If none are found it defaults to no overlay.

**Comment by obsidian-dot-dev** [comment] 2024-02-26 22:22
Thanks for the feedback - there have been a couple of reports and suggestions similar to yours, and there will be some form of automatic overlay loading supported in a subsequent release.  Closing as a duplicate of issue #4  and #2.

**Closed as not planned by obsidian-dot-dev** 2024-02-26 22:22 UTC

**Comment by b-mag** [comment] 2024-02-26 23:00
Thank you. Definitely consider defaulting to no overlay and supporting straight .bin files which is how these games are used and built in the community.  As a Vectrex developer running my games on here without forcing arbitrary file extension would be excellent.

**Comment by b-mag** [comment] 2024-02-27 21:02
Should I create another request for the .bin support? All games are distributed in this format and .Vec is not. This in turn would require average users to rename potentially hundreds of games. There are a lot more than the original 28!

**Comment by b-mag** [comment] 2024-02-27 21:03
I realize though you are basing it from mister but I assume it shouldn't be too much to support both extensions?
